### PR TITLE
Add docs for new wallet api

### PR DESCRIPTION
**Pull request by candida-d**
Add a new API section for Vega Wallet as of 0.54

- Add overview
- Add OpenRPC page (generated by [vegaprotocol/openrpc-md](https://github.com/vegaprotocol/openrpc-md))
- Add a page with an embedded [Open RPC playground ](https://github.com/open-rpc/playground)

Undrafted now #194 is merged

### CODE REVIEW

**Comment by mattrussell36** [comment]
@candida-d Heres some feedback on the docs.

- Getting started 
  - In the top section I think the structure could be better. Rather than having the green and yellow callouts I think some regular sub headings, one for JSON RPC (and a link to the docs), and one for software compatibility would be easier to read.
  - In the bottom section I'd leave out the bullet for method, params, id. Its all in the json rpc docs and examples.
- OpenRPC Wallet API
  - I think it would be good to see all available methods in a concise list, a contents section if you will, which link to the detailed ection for the method. I realise this is in the playground too but I think it would be good here. Its probably the first thing a lot of people will look for and the playground can be slow to load.
  - The tables for Parameters and Result have a description column which is often empty. Would be good to fill these in if possible or remove?
  - Just a personal visual thing for me but the code block in the result title makes things look too busy.
 Screen Shot 2022-08-20 at 11 39 08 PM
  - I find the top section a little busy. IMO it would be cleaner to remove the green callout for the playground and move the yellow callout about versioning into its place. 
Screen Shot 2022-08-20 at 11 41 35 PM
  - Do we need the quote block here? It kind of just repeats the same info and makes things a little cluttered
Screen Shot 2022-08-20 at 11 43 18 PM

**Comment by edd** [comment]
I've addressed lots of @mattrussell36's feedback in a newly regenerated page:
- Green header is gone for now. We added it manually, so regenerating just... removed it. I think that's OK now that it's in the sidebar, which it wasn't when we added the header
- Added backticks around the method headers, which makes them stand out better
- Added a TOC at the start that contains the name and the summary and links to the method section
- Removed the summary underneath the method header, which helps reduce the over-formatting
- ENUM params are now formatted better

**Review by mattrussell36 — APPROVED** [review]

**Comment by mattrussell36** [comment]
A couple other things.

- For whatever reason I found it hard to find what the actual jsonrpc endpoint was. I feel like this should be more prominent somewhere. Perhaps a full section on getting started?
- Typo in session.request_permissions in the reference page. The permission params should be `public_keys` not `public_key`

**Comment by candida-d** [comment]
@ValentinTrinque I think this one is for you: 

> Typo in session.request_permissions in the reference page. The permission params should be public_keys not public_key

**Comment by candida-d** [comment]
> 
>     * For whatever reason I found it hard to find what the actual jsonrpc endpoint was. I feel like this should be more prominent somewhere. Perhaps a full section on getting started?

@mattrussell36 I've added the endpoint to the top of the page, where it already says what kind of API it is. Is that clearer now?

**Comment by edd** [comment]
I *think* this closes https://github.com/vegaprotocol/documentation/issues/179, assuming the tools links are updated

**Pull request merged**
