### PR TITLE
Add initial Docusaurus config plus auto-generated docs

### PR DESCRIPTION
**Pull request by ashleyvega**
This PR:
- adds Docusaurus config
- adds auto-generated **gRPC** documentation at `/protodocs/` using [docusaurus-protobuffet](https://www.npmjs.com/package/docusaurus-protobuffet) and [`api:grpc/doc/doc.json`](https://github.com/vegaprotocol/api/blob/develop/grpc/doc/doc.json)
- adds auto-generated **GraphQL** documentation at `/docs/graphql/` using [docusaurus2-graphql-doc-generator](https://www.npmjs.com/package/@edno/docusaurus2-graphql-doc-generator) and [`api:graphql/schema.graphql`](https://github.com/vegaprotocol/api/blob/develop/graphql/schema.graphql)
- adds auto-generated **REST** documentation at `/docs/rest/` using [redocusaurus](https://www.npmjs.com/package/redocusaurus) and [`api:rest/api/trading.swagger.json`](https://github.com/vegaprotocol/api/blob/develop/rest/api/trading.swagger.json)

To do in another Issue: Get **gRPC** docs to appear at `/docs/grpc/` and not `/protodocs/`. Problem: The string "protodocs" seems to be hard-coded in the code that does the autogeneration, so when the config specifies `/grpc/` and not `/protodocs/`, we get "dir not found: protodocs".

### CODE REVIEW

**Comment by candida-d** [comment]
It is so cool to see how this is progressing! Looks like a real improvement so far.

**Comment by candida-d** [comment]
Question @ashleyvega - Can all the api docs live in the same folder, so the file structure is consistent? 

As it's currently: 
/docs/graphql/
/protodocs/vega.proto

**Comment by ashleyvega** [comment]
I'm willing to spend some amount of time ~~banging my head against a wall~~ investigating how to fix the dir paths and still get everything built.

**Comment by candida-d** [comment]
@ashleyvega I figured there was a reason for it. That's a shame but I think it's still a better layout than we currently have live. If you're willing and able to spend the time on it, that would be very much appreciated! Is there anyone else who you think might have extra knowledge or ideas? I can at least try to rope someone in.

**Comment by ashleyvega** [comment]
@candida-d Since the plugins are all from npmjs, someone from Team UI/Console would be best.

**Comment by edd** [comment]
At the very worst we can use redirects so that you can give someone a nice URL as a starting point. That's not a good solution, but it would let us link to /docs/rest, /docs/graphql like we do now.

I will ask in the channel if someone can take a look

**Comment by candida-d** [comment]
Design - There's still some dark-on-dark text in a few places: screenshot


Function: 
The "edit this page" buttons go to a 404. That's expected right now because the branch moves the files around. However I don't think "edit this page" should exist on the auto-gen docs since they're not really editable via this repo. 
<details><summary>Browser metadata</summary>





```
Path:      /docs/graphql/schema/
Browser:   Firefox 88.0 on Mac OS 10.15
Viewport:  1532 x 856 @2x
Language:  en-GB
Cookies:   Enabled
```

[View on BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-2--silly-jepsen-adff2b.netlify.app%2Fdocs%2Fgraphql%2Fschema%2F&os=OS+X&os_version=Catalina&browser=Firefox&browser_version=88.0&resolution=1532x856&speed=1&start=true)



</details>

[Open Deploy Preview](https://deploy-preview-2--silly-jepsen-adff2b.netlify.app/docs/graphql/schema/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60ba397c177ef900071b9b83&commentID=60ba5a9c1861d36232d973fd&resolution=resolved)

**Comment by candida-d** [comment]
Next steps for me are to think about the IA and how to incorporate the non-autogen docs, and probably work with @ashleyvega on how to get the different sections to display in a way that means easy discoverability and navigation.

**Comment by candida-d** [comment]
To-do: Look into search - algolia looks great but might be enterprise/not open source? Lots of docusaurus docs are using it as the search option.

**Comment by candida-d** [comment]
Let's do it!

**Pull request merged**
