### PR TITLE
feat: add smart contract upgrade step by step guide

### PR DESCRIPTION
**Pull request by jeremyletang**
Start work on smart contract upgrade step by step guide.

### CODE REVIEW

**Review by emilbayes — APPROVED** [review]
Only last "issue" is the menu item with this page appears as "migration-guide" in the sidebar

**Comment by candida-d** [comment]
> Only last "issue" is the menu item with this page appears as "migration-guide" in the sidebar

I'll fix that :)

**Comment by candida-d** [comment]
@emilbayes that's done now, let me know if you come up with a more interesting section title and I can change it

**Comment by emilbayes** [comment]
@candida-d "Migration Guides" would be good enough for me :) It's mostly that right now it looks like part of an url in the sidebar and not a section title

**Pull request merged**
